name: Frontend Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:

defaults:
  run:
    working-directory: client

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: /home/runner/work/Pokemon-EV-Trainer/Pokemon-EV-Trainer/client/build

  deploy:
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4